import React, { useEffect, useState, useRef, useMemo, useLayoutEffect } from 'react';
import useAnimateRoute from '../../hooks/useAnimatedRoute';
import './gallerypage.css';
import { Logo } from '../../components';
import { Fancybox } from '@fancyapps/ui';
import '@fancyapps/ui/dist/fancybox/fancybox.css';
import { manifestToItems, buildRows } from './galleryLayout';

const MANIFEST_URL = `${process.env.PUBLIC_URL}/gallery/manifest.json`;

function GalleryPage() {
  const [items, setItems] = useState([]);
  const animationClass = useAnimateRoute();

  const containerRef = useRef(null);
  const [containerWidth, setContainerWidth] = useState(0);

  // Load the photo manifest (filenames + dimensions) generated by `npm run photos`.
  useEffect(() => {
    let cancelled = false;
    fetch(MANIFEST_URL)
      .then((res) => (res.ok ? res.json() : Promise.reject(new Error(`HTTP ${res.status}`))))
      .then((data) => {
        if (!cancelled) setItems(manifestToItems(data));
      })
      .catch((err) => console.error('Failed to load gallery manifest:', err));
    return () => {
      cancelled = true;
    };
  }, []);

  // Track the container's inner width so rows can justify to it on resize.
  useLayoutEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const update = () => setContainerWidth(el.clientWidth);
    update();
    const ro = new ResizeObserver(update);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  // Open a full-resolution in-page lightbox on click.
  useEffect(() => {
    Fancybox.bind('[data-fancybox="gallery"]', {});
    return () => {
      Fancybox.unbind('[data-fancybox="gallery"]');
      Fancybox.close();
    };
  }, []);

  const rows = useMemo(() => buildRows(items, containerWidth), [items, containerWidth]);

  return (
    <div className={animationClass}>
      <div className='gallerypage-body'>
        <h1>Gallery</h1>
        <hr></hr>
        <p> My attempt at photography. Older photos were taken with an Olympus E-PL6.</p>
        <p>Current Camera: Sony A6700</p>
        <p>Lens: Sigma 17-40mm f/1.8</p>
        <br></br>
        <b><span id="images-count">{items.length}</span></b> pictures
        <div id="images-container" ref={containerRef}>
          {rows.map((row, ri) => (
            <div className="gallery-row" key={ri} style={{ height: row.height }}>
              {row.items.map((item) => (
                <a
                  key={item.id}
                  className="gallery-item"
                  style={{ width: item.ar * row.height }}
                  target="_blank"
                  rel="noreferrer"
                  href={`${process.env.PUBLIC_URL}${item.lightboxUrl}`}
                  data-fancybox="gallery"
                  data-type="image"
                >
                  <img
                    src={`${process.env.PUBLIC_URL}${item.thumbnailUrl}`}
                    alt="a picture"
                    className="thumbnail"
                    loading="lazy"
                    decoding="async"
                  />
                </a>
              ))}
            </div>
          ))}
        </div>
      </div>
      <Logo></Logo>
    </div>
  );
}

export default GalleryPage;
